buildroot: use buildroot from official repo as submodule
showmewebcam/showmewebcam pull request #187
Opened 2022-01-23 01:53 UTC by GDGooD

There are several pros to use these git feature:
 - no need to download from external site, less steps to start to
   build the project
 - easy to set a new version of buildroot and keep it updated
 - there is risk that the project will not be compatible with newer
   versions of buildroot, so the older version of the project
   will be rebuildable (starting with this patch)

Let's use version 2021.02.8 as it still buildable with the project.

Signed-off-by: Dmytro Kropenko <k.dmitriu@gmail.com>

2022-01-24 08:53 UTC, dgsiegel commented
Thanks for this PR, looks very nice so far.

Two things:

- I *think* it'd be possible to add a tag instead of a commit id in the submodule. If that is possible, I'd prefer using that.
- You've missed our build process (https://github.com/showmewebcam/showmewebcam/blob/master/.github/workflows/release.yml#L61) which downloads buildroot manually. Would you mind expanding your PR to include that?

Thanks!

2022-01-24 23:36 UTC, GDGooD commented
Hello, @dgsiegel 

 - Unfortunately there is no way to track tag for submodule, only using commit hash. At least, we can check a version inside submodule directory via `git describe`.
 - Build process is updated, but need to verify it as I have no experience with that.
 
 Best regards

2022-01-25 17:38 UTC, dgsiegel commented
See my other comments. I've enabled automatic checks for this PR, so you should be able to see whether your patch succeeds.

Thanks!

2022-01-27 18:53 UTC, GDGooD commented
Looks like everything is passed, and raspberrypi0w build successfuly works on my RPi.

2022-01-27 19:04 UTC, htruong submitted a review, later dismissed

2022-01-27 19:50 UTC, dgsiegel commented
Awesome! Would you mind resolving my remaining comments above? After that we can merge this PR.

2022-01-27 22:36 UTC, GDGooD commented
I can not find any comments here. Can you help with finding them?

2022-01-27 23:35 UTC, dgsiegel commented
Just scroll up here :) They should also be visible in the "Files changed" tab.

2022-01-28 01:08 UTC, GDGooD commented
I really can not see any of them. Maybe something wrong with rigth access?

2022-01-28 10:18 UTC, dgsiegel requested changes

2022-01-28 10:18 UTC, dgsiegel commented
Can you see them now?

2022-02-03 00:14 UTC, GDGooD commented on README.md
> -  - **IMPORTANT**: If you didn't rename your Buildroot directory to `buildroot` or if you put it somewhere else you need to set the Buildroot path manually, e.g. `BUILDROOT_DIR=../buildroot ./build-s
Changed "important" to "note" as it no more critical information.

2022-02-03 00:15 UTC, GDGooD commented on .github/workflows/release.yml
> +      BUILDROOT_VERSION: '2021.02.8'
Replaced with commit id.

2022-02-03 00:16 UTC, GDGooD commented on .github/workflows/release.yml
> +          git submodule update
Step removed, set "submodules" option to "recursive".

2022-02-03 17:11 UTC, dgsiegel commented
Thanks for updating your PR. I think we can merge it now, there's just a few minor comments I've added above.

2022-02-03 17:12 UTC, dgsiegel commented on .github/workflows/release.yml
> +      BUILDROOT_VERSION: '2021.02.8'
We can definitely remove this line. But I can't see where you've used a commit id? The only place where we'd use it is for the cache key:

`          key: ${{ matrix.raspberry }}-${{ env.BUILDROOT_DIR }}-${{ env.BUILDROOT_VERSION }}-${{ secrets.CACHE_VERSION }}`

2022-02-03 17:14 UTC, dgsiegel commented on .github/workflows/release.yml
> +          git submodule update
The mentioned action has support for including submodules when checking out the repo. What's advantage of doing this manually here?

2022-02-04 01:03 UTC, GDGooD commented on .github/workflows/release.yml
> +          git submodule update
My bad, git add didn't select this file. Please, review again.

2022-02-04 01:03 UTC, GDGooD commented on .github/workflows/release.yml
> +      BUILDROOT_VERSION: '2021.02.8'
My bad, git add didn't select this file. Please, review again.

2022-02-04 15:04 UTC, dgsiegel approved these changes

2022-02-04 15:05 UTC, merged